// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdCf6ZNBz2XvkjdTYihbw09UQUECmddLA',
    appId: '1:876723832873:web:debea1b0ffceedde22f438',
    messagingSenderId: '876723832873',
    projectId: 'teamomart',
    authDomain: 'teamomart.firebaseapp.com',
    storageBucket: 'teamomart.firebasestorage.app',
    measurementId: 'G-1F6NC0V5HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ3Un7d7JXXek3u3_oAOjboy8xD3dmloU',
    appId: '1:876723832873:android:15e506b589996ce922f438',
    messagingSenderId: '876723832873',
    projectId: 'teamomart',
    storageBucket: 'teamomart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBOdmMgP-19e34mHDXVwODjn7IItfZSY4',
    appId: '1:876723832873:ios:ee30ba53dc80ff0c22f438',
    messagingSenderId: '876723832873',
    projectId: 'teamomart',
    storageBucket: 'teamomart.firebasestorage.app',
    iosBundleId: 'com.example.teamomarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBOdmMgP-19e34mHDXVwODjn7IItfZSY4',
    appId: '1:876723832873:ios:ee30ba53dc80ff0c22f438',
    messagingSenderId: '876723832873',
    projectId: 'teamomart',
    storageBucket: 'teamomart.firebasestorage.app',
    iosBundleId: 'com.example.teamomarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdCf6ZNBz2XvkjdTYihbw09UQUECmddLA',
    appId: '1:876723832873:web:beac50c4635184dc22f438',
    messagingSenderId: '876723832873',
    projectId: 'teamomart',
    authDomain: 'teamomart.firebaseapp.com',
    storageBucket: 'teamomart.firebasestorage.app',
    measurementId: 'G-1L6KWM9B9M',
  );
}
