import '../models/product_model.dart';

final now = DateTime.now();

final List<ProductModel> dummyProducts = [

  /// 1
  ProductModel(
    id: "P001",
    title: "Samsung Galaxy S24 Ultra",
    description:
    "Brand new Samsung Galaxy S24 Ultra 256GB with original bill and warranty.",
    price: 78999,
    type: ProductType.sell,
    categoryId: "mobiles",
    subCategoryId: "android",
    sellerId: "USER001",
    agentId: "AG001",
    images: [
      "https://picsum.photos/600/600?1",
      "https://picsum.photos/600/600?2",
    ],
    attributes: {
      "brand": "Samsung",
      "model": "S24 Ultra",
      "storage": "256 GB",
      "color": "Titanium Black",
      "condition": ProductCondition.newProduct,
    },
    // condition: ProductCondition.newProduct,
    country: "India",
    state: "Bihar",
    city: "Patna",
    area: "Kankarbagh",
    latitude: 25.5941,
    longitude: 85.1376,
    status: ProductStatus.active,
    isNegotiable: true,
    isFeatured: true,
    // isNew: true,
    isVerified: true,
    isUrgent: false,
    views: 542,
    likes: 94,
    shares: 15,
    chats: 28,
    publishedAt: now,
    allowComments: true,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 2
  ProductModel(
    id: "P002",
    title: "Hyundai Verna SX",
    description:
    "2019 Diesel | First Owner | Service Record Available",
    price: 685000,
    type: ProductType.sell,
    categoryId: "cars",
    subCategoryId: "sedan",
    sellerId: "USER002",
    images: [
      "https://picsum.photos/600/600?3",
    ],
    attributes: {
      "brand": "Hyundai",
      "year": 2019,
      "fuel": "Diesel",
      "transmission": "Manual",
      "condition": ProductCondition.good,
    },
    // condition: ProductCondition.good,
    country: "India",
    state: "Delhi",
    city: "Delhi",
    area: "Rohini",
    status: ProductStatus.active,
    isNegotiable: false,
    isFeatured: true,
    isVerified: true,
    views: 710,
    likes: 132,
    shares: 32,
    chats: 41,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 3
  ProductModel(
    id: "P003",
    title: "Looking for 2BHK Apartment",
    description:
    "Need a 2BHK apartment near Sector 62 Metro.",
    price: 3000000,
    type: ProductType.buy,
    categoryId: "property",
    subCategoryId: "flat",
    sellerId: "USER003",
    images: const [],
    attributes: {
      "bhk": 2,
      "purpose": "Buy",
      "condition": ProductCondition.newProduct,
    },
    // condition: ProductCondition.newProduct,
    country: "India",
    state: "Uttar Pradesh",
    city: "Noida",
    area: "Sector 62",
    status: ProductStatus.active,
    isNegotiable: true,
    isUrgent: true,
    views: 184,
    likes: 21,
    shares: 4,
    chats: 17,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 4
  ProductModel(
    id: "P004",
    title: "Apple MacBook Air M2",
    description:
    "8GB RAM • 256GB SSD • Warranty till 2027",
    price: 82999,
    type: ProductType.sell,
    categoryId: "electronics",
    subCategoryId: "laptop",
    sellerId: "USER004",
    images: [
      "https://picsum.photos/600/600?4",
    ],
    attributes: {
      "brand": "Apple",
      "processor": "M2",
      "ram": "8 GB",
      "storage": "256 GB",
      "condition": ProductCondition.likeNew,
    },
    // //   condition: ProductCondition.likeNew,
    country: "India",
    state: "Maharashtra",
    city: "Mumbai",
    area: "Andheri",
    status: ProductStatus.active,
    isNegotiable: true,
    isVerified: true,
    views: 876,
    likes: 188,
    shares: 44,
    chats: 56,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 5
  ProductModel(
    id: "P005",
    title: "Yamaha R15 V4",
    description:
    "2023 Model | Single Owner | Excellent Condition",
    price: 158000,
    type: ProductType.sell,
    categoryId: "bikes",
    subCategoryId: "sports",
    sellerId: "USER005",
    images: [
      "https://picsum.photos/600/600?5",
    ],
    attributes: {
      "brand": "Yamaha",
      "model": "R15 V4",
      "year": 2023,
      "condition": ProductCondition.likeNew,
    },
    // //   condition: ProductCondition.likeNew,
    country: "India",
    state: "Karnataka",
    city: "Bengaluru",
    area: "Whitefield",
    status: ProductStatus.active,
    isNegotiable: true,
    isUrgent: true,
    views: 421,
    likes: 62,
    shares: 8,
    chats: 29,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),
  /// 6
  ProductModel(
    id: "P006",
    title: "L Shape Sofa Set",
    description:
    "Premium fabric L-shaped sofa with center table. Hardly used.",
    price: 24500,
    type: ProductType.sell,
    categoryId: "furniture",
    subCategoryId: "sofa",
    sellerId: "USER006",
    images: [
      "https://picsum.photos/600/600?6",
    ],
    attributes: {
      "material": "Fabric",
      "color": "Grey",
      "seats": 5,
    },
    // condition: ProductCondition.good,
    country: "India",
    state: "West Bengal",
    city: "Kolkata",
    area: "Salt Lake",
    status: ProductStatus.active,
    isNegotiable: true,
    views: 216,
    likes: 27,
    shares: 6,
    chats: 11,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 7
  ProductModel(
    id: "P007",
    title: "3 BHK Luxury Apartment",
    description:
    "Semi furnished apartment with parking and lift.",
    price: 8500000,
    type: ProductType.sell,
    categoryId: "property",
    subCategoryId: "apartment",
    sellerId: "USER007",
    images: [
      "https://picsum.photos/600/600?7",
    ],
    attributes: {
      "bhk": 3,
      "bathrooms": 2,
      "area": "1650 sqft",
      "parking": true,
      "condition": ProductCondition.newProduct,
    },
    country: "India",
    state: "Telangana",
    city: "Hyderabad",
    area: "Gachibowli",
    status: ProductStatus.active,
    isFeatured: true,
    isVerified: true,
    views: 980,
    likes: 154,
    shares: 47,
    chats: 62,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 8
  ProductModel(
    id: "P008",
    title: "Golden Retriever Puppy",
    description:
    "Healthy vaccinated male puppy with vaccination card.",
    price: 18000,
    type: ProductType.sell,
    categoryId: "pets",
    subCategoryId: "dogs",
    sellerId: "USER008",
    images: [
      "https://picsum.photos/600/600?8",
    ],
    attributes: {
      "breed": "Golden Retriever",
      "age": "3 Months",
      "gender": "Male",
      "condition": ProductCondition.newProduct,
    },
    // condition: ProductCondition.newProduct,
    country: "India",
    state: "Punjab",
    city: "Ludhiana",
    area: "Model Town",
    status: ProductStatus.active,
    isUrgent: true,
    views: 641,
    likes: 118,
    shares: 20,
    chats: 35,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 9
  ProductModel(
    id: "P009",
    title: "Sony PlayStation 5",
    description:
    "Disc Edition with one controller and original box.",
    price: 42000,
    type: ProductType.sell,
    categoryId: "gaming",
    subCategoryId: "console",
    sellerId: "USER009",
    images: [
      "https://picsum.photos/600/600?9",
    ],
    attributes: {
      "brand": "Sony",
      "storage": "825 GB",
      "edition": "Disc",
    },
    // //   condition: ProductCondition.likeNew,
    country: "India",
    state: "Tamil Nadu",
    city: "Chennai",
    area: "Anna Nagar",
    status: ProductStatus.active,
    isFeatured: true,
    views: 803,
    likes: 176,
    shares: 38,
    chats: 49,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 10
  ProductModel(
    id: "P010",
    title: "Men's Leather Jacket",
    description:
    "Premium genuine leather jacket. Size XL.",
    price: 4500,
    type: ProductType.sell,
    categoryId: "fashion",
    subCategoryId: "mens_wear",
    sellerId: "USER010",
    images: [
      "https://picsum.photos/600/600?10",
    ],
    attributes: {
      "brand": "Zara",
      "size": "XL",
      "color": "Black",
      "condition": ProductCondition.newProduct,
    },
    // //   condition: ProductCondition.likeNew,
    country: "India",
    state: "Rajasthan",
    city: "Jaipur",
    area: "Malviya Nagar",
    status: ProductStatus.active,
    isNegotiable: true,
    views: 341,
    likes: 52,
    shares: 10,
    chats: 16,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),
  /// 11
  ProductModel(
    id: "P011",
    title: "Apple iPhone 15 Pro Max",
    description: "256GB Natural Titanium with Apple warranty.",
    price: 112000,
    type: ProductType.sell,
    categoryId: "mobiles",
    subCategoryId: "iphone",
    sellerId: "USER011",
    images: ["https://picsum.photos/600/600?11"],
    attributes: {
      "brand": "Apple",
      "storage": "256 GB",
      "color": "Natural Titanium",
    },
    // //   condition: ProductCondition.likeNew,
    country: "India",
    state: "Maharashtra",
    city: "Pune",
    area: "Hinjewadi",
    status: ProductStatus.active,
    isFeatured: true,
    isVerified: true,
    views: 1135,
    likes: 264,
    shares: 58,
    chats: 91,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 12
  ProductModel(
    id: "P012",
    title: "Toyota Fortuner 4x4",
    description: "2022 Diesel Automatic | Excellent Condition.",
    price: 3850000,
    type: ProductType.sell,
    categoryId: "cars",
    subCategoryId: "suv",
    sellerId: "USER012",
    images: ["https://picsum.photos/600/600?12"],
    attributes: {
      "brand": "Toyota",
      "year": 2022,
      "fuel": "Diesel",
      "transmission": "Automatic",
    },
    // //   condition: ProductCondition.likeNew,
    country: "India",
    state: "Gujarat",
    city: "Ahmedabad",
    area: "Satellite",
    status: ProductStatus.active,
    isFeatured: true,
    isVerified: true,
    views: 1340,
    likes: 327,
    shares: 79,
    chats: 102,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 13
  ProductModel(
    id: "P013",
    title: "Looking for Rental House",
    description: "Need 2BHK house near city center.",
    price: 18000,
    type: ProductType.buy,
    categoryId: "property",
    subCategoryId: "house",
    sellerId: "USER013",
    images: const [],
    attributes: {
      "bhk": 2,
      "purpose": "Rent",
    },
    // condition: ProductCondition.good,
    country: "India",
    state: "Jharkhand",
    city: "Ranchi",
    area: "Harmu",
    status: ProductStatus.active,
    isUrgent: true,
    views: 164,
    likes: 19,
    shares: 3,
    chats: 22,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 14
  ProductModel(
    id: "P014",
    title: "Software Developer Required",
    description: "Flutter Developer with 2+ years experience.",
    price: 900000,
    type: ProductType.sell,
    categoryId: "jobs",
    subCategoryId: "it",
    sellerId: "USER014",
    images: ["https://picsum.photos/600/600?14"],
    attributes: {
      "experience": "2 Years",
      "employment": "Full Time",
    },
    // condition: ProductCondition.newProduct,
    country: "India",
    state: "Karnataka",
    city: "Bengaluru",
    area: "Electronic City",
    status: ProductStatus.active,
    isFeatured: true,
    views: 692,
    likes: 81,
    shares: 21,
    chats: 43,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 15
  ProductModel(
    id: "P015",
    title: "LG Front Load Washing Machine",
    description: "7 Kg Fully Automatic.",
    price: 18500,
    type: ProductType.sell,
    categoryId: "electronics",
    subCategoryId: "washing_machine",
    sellerId: "USER015",
    images: ["https://picsum.photos/600/600?15"],
    attributes: {
      "brand": "LG",
      "capacity": "7 Kg",
    },
    //condition: ProductCondition.good,
    country: "India",
    state: "Kerala",
    city: "Kochi",
    area: "Edappally",
    status: ProductStatus.active,
    isNegotiable: true,
    views: 296,
    likes: 37,
    shares: 8,
    chats: 14,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 16
  ProductModel(
    id: "P016",
    title: "Canon EOS 1500D DSLR",
    description: "With 18-55 Lens & Bag.",
    price: 32000,
    type: ProductType.sell,
    categoryId: "camera",
    subCategoryId: "dslr",
    sellerId: "USER016",
    images: ["https://picsum.photos/600/600?16"],
    attributes: {
      "brand": "Canon",
      "resolution": "24.1 MP",
    },
    //   condition: ProductCondition.likeNew,
    country: "India",
    state: "Uttar Pradesh",
    city: "Lucknow",
    area: "Gomti Nagar",
    status: ProductStatus.active,
    isVerified: true,
    views: 411,
    likes: 54,
    shares: 11,
    chats: 19,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 17
  ProductModel(
    id: "P017",
    title: "Engineering Books Bundle",
    description: "Complete CSE Semester books.",
    price: 2800,
    type: ProductType.sell,
    categoryId: "books",
    subCategoryId: "education",
    sellerId: "USER017",
    images: ["https://picsum.photos/600/600?17"],
    attributes: {
      "subject": "Computer Science",
    },
    // condition: ProductCondition.good,
    country: "India",
    state: "Bihar",
    city: "Gaya",
    area: "Civil Lines",
    status: ProductStatus.active,
    views: 148,
    likes: 16,
    shares: 2,
    chats: 5,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 18
  ProductModel(
    id: "P018",
    title: "Firefox Mountain Bicycle",
    description: "21 Speed Alloy Frame.",
    price: 13500,
    type: ProductType.sell,
    categoryId: "sports",
    subCategoryId: "cycle",
    sellerId: "USER018",
    images: ["https://picsum.photos/600/600?18"],
    attributes: {
      "brand": "Firefox",
      "frame": "Alloy",
    },
    // condition: ProductCondition.good,
    country: "India",
    state: "Madhya Pradesh",
    city: "Indore",
    area: "Vijay Nagar",
    status: ProductStatus.active,
    isNegotiable: true,
    views: 271,
    likes: 33,
    shares: 6,
    chats: 9,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 19
  ProductModel(
    id: "P019",
    title: "Home Painting Service",
    description: "Professional painters for home & office.",
    price: 5000,
    type: ProductType.sell,
    categoryId: "services",
    subCategoryId: "painting",
    sellerId: "USER019",
    images: ["https://picsum.photos/600/600?19"],
    attributes: {
      "service": "Painting",
      "experience": "8 Years",
    },
    // condition: ProductCondition.newProduct,
    country: "India",
    state: "Odisha",
    city: "Bhubaneswar",
    area: "Patia",
    status: ProductStatus.active,
    isVerified: true,
    views: 223,
    likes: 28,
    shares: 4,
    chats: 13,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),

  /// 20
  ProductModel(
    id: "P020",
    title: "22K Gold Necklace",
    description: "Hallmarked Gold Necklace.",
    price: 98000,
    type: ProductType.sell,
    categoryId: "jewellery",
    subCategoryId: "gold",
    sellerId: "USER020",
    images: ["https://picsum.photos/600/600?20"],
    attributes: {
      "purity": "22K",
      "weight": "18 gm",
    },
    // condition: ProductCondition.newProduct,
    country: "India",
    state: "West Bengal",
    city: "Kolkata",
    area: "Park Street",
    status: ProductStatus.active,
    isFeatured: true,
    isVerified: true,
    views: 845,
    likes: 165,
    shares: 27,
    chats: 48,
    publishedAt: now,
    createdAt: now,
    updatedAt: now, sellerName: '', sellerPhoto: '',
  ),
];