import '../../../../../modules/category/models/category_model.dart';

final now = DateTime.now();

final List<CategoryModel> categories = [
  CategoryModel(
    id: "cars",
    name: "Cars",
    image: "assets/categories/car.png",
    order: 1,
    color: "#EF4444",
    isFeatured: true,
    hasSubCategories: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "mobiles",
    name: "Mobiles",
    image: "assets/categories/mobile.png",
    order: 2,
    color: "#3B82F6",
    isFeatured: true,
    hasSubCategories: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "property",
    name: "Property",
    image: "assets/categories/property.png",
    order: 3,
    color: "#10B981",
    isFeatured: true,
    hasSubCategories: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "fashion",
    name: "Fashion",
    image: "assets/categories/fashion.png",
    order: 4,
    color: "#EC4899",
    hasSubCategories: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "jobs",
    name: "Jobs",
    image: "assets/categories/jobs.png",
    order: 5,
    color: "#F59E0B",
    hasSubCategories: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "bikes",
    name: "Bikes",
    image: "assets/categories/bikes.png",
    order: 6,
    color: "#6366F1",
    hasSubCategories: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "furniture",
    name: "Furniture",
    image: "assets/categories/furniture.png",
    order: 7,
    color: "#8B5CF6",
    hasSubCategories: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "services",
    name: "Services",
    image: "assets/categories/service.png",
    order: 8,
    color: "#06B6D4",
    hasSubCategories: false,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "electronics",
    name: "Electronics",
    image: "assets/categories/electronics.png",
    order: 9,
    color: "#14B8A6",
    hasSubCategories: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "pets",
    name: "Pets",
    image: "assets/categories/pets.png",
    order: 10,
    color: "#A855F7",
    hasSubCategories: true,
    createdAt: now,
    updatedAt: now,
  ),

];