import '../../../../../modules/category/models/category_model.dart';

final now = DateTime.now();

final List<CategoryModel> categories = [
  CategoryModel(
    id: "1",
    title: "Cars",
    image: "assets/categories/car.png",
    order: 1,
    color: "#EF4444",
    isFeatured: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "2",
    title: "Mobiles",
    image: "assets/categories/mobile.png",
    order: 2,
    color: "#3B82F6",
    isFeatured: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "3",
    title: "Property",
    image: "assets/categories/property.png",
    order: 3,
    color: "#10B981",
    isFeatured: true,
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "4",
    title: "Fashion",
    image: "assets/categories/fashion.png",
    order: 4,
    color: "#EC4899",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "5",
    title: "Jobs",
    image: "assets/categories/jobs.png",
    order: 5,
    color: "#F59E0B",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "6",
    title: "Bikes",
    image: "assets/categories/bikes.png",
    order: 6,
    color: "#6366F1",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "7",
    title: "Furniture",
    image: "assets/categories/furniture.png",
    order: 7,
    color: "#8B5CF6",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "8",
    title: "Services",
    image: "assets/categories/service.png",
    order: 8,
    color: "#06B6D4",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "9",
    title: "Electronics",
    image: "assets/categories/electronics.png",
    order: 9,
    color: "#14B8A6",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "10",
    title: "Pets",
    image: "assets/categories/pets.png",
    order: 10,
    color: "#A855F7",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "11",
    title: "Computers & Laptops",
    image: "assets/categories/computer.png",
    order: 11,
    color: "#0F766E",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "12",
    title: "Home Appliances",
    image: "assets/categories/appliances.png",
    order: 12,
    color: "#EA580C",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "13",
    title: "Books",
    image: "assets/categories/books.png",
    order: 13,
    color: "#F97316",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "14",
    title: "Sports & Fitness",
    image: "assets/categories/sports.png",
    order: 14,
    color: "#22C55E",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "15",
    title: "Kids & Babies",
    image: "assets/categories/kids.png",
    order: 15,
    color: "#FACC15",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "16",
    title: "Beauty & Personal Care",
    image: "assets/categories/beauty.png",
    order: 16,
    color: "#DB2777",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "17",
    title: "Agriculture",
    image: "assets/categories/agriculture.png",
    order: 17,
    color: "#65A30D",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "18",
    title: "Commercial Vehicles",
    image: "assets/categories/commercial.png",
    order: 18,
    color: "#7C3AED",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "19",
    title: "Spare Parts",
    image: "assets/categories/spare_parts.png",
    order: 19,
    color: "#DC2626",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "20",
    title: "Tools & Machinery",
    image: "assets/categories/tools.png",
    order: 20,
    color: "#0EA5E9",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "21",
    title: "Musical Instruments",
    image: "assets/categories/music.png",
    order: 21,
    color: "#9333EA",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "22",
    title: "Gaming",
    image: "assets/categories/gaming.png",
    order: 22,
    color: "#2563EB",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "23",
    title: "Cameras",
    image: "assets/categories/camera.png",
    order: 23,
    color: "#4B5563",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "24",
    title: "Watches",
    image: "assets/categories/watch.png",
    order: 24,
    color: "#6D28D9",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "25",
    title: "Jewellery",
    image: "assets/categories/jewellery.png",
    order: 25,
    color: "#D97706",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "26",
    title: "Office Equipment",
    image: "assets/categories/office.png",
    order: 26,
    color: "#475569",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "27",
    title: "Events",
    image: "assets/categories/event.png",
    order: 27,
    color: "#BE123C",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "28",
    title: "Travel & Tourism",
    image: "assets/categories/travel.png",
    order: 28,
    color: "#0891B2",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "29",
    title: "Education",
    image: "assets/categories/education.png",
    order: 29,
    color: "#16A34A",
    createdAt: now,
    updatedAt: now,
  ),
  CategoryModel(
    id: "30",
    title: "Others",
    image: "assets/categories/other.png",
    order: 30,
    color: "#6B7280",
    createdAt: now,
    updatedAt: now,
  ),
];